apiVersion: v1       # api version v1beta1 ---- crd custom resorce defination 
kind: Pod            # resource deployenent service namespace 
metadata:            # genrel info collect name label annotations and namespace 
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:                # specification containers volume 
  containers:                    
  - name: myapp                         
    image: <Image>                            
    resources:                        # limits --- cpu memory, requests limits ;; oomkillerror, crashbackloopoff 
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>         # container port ----- image 
