apiVersion: apps/v1
kind: Deployment
metadata:
  name: example1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example1
    spec:
      containers:
      - name: example1
        image: nginx:latest
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: component
                operator: In
                values:
                - infra
              - matchExpressions:
                key: apps
                operator: In
                values:
                - infra 