apiVersion: v1
kind: Namespace
metadata:
  name: postgresql 

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secret
  namespace: postgresql 
type: Opaque
data:
  password: ZmxlY3RyYWcxMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: postgresql 
type: Opaque
data:
  password: ZmxlY3RyYWcxMjM=